export { default as Footer} from './footer/Footer'
export { default as HeaderContent} from './headercontent/HeaderContent'
export { default as IntroContent} from './introcontent/IntroContent'
export { default as GalleryContent} from './gallerycontent/GalleryContent'
export { default as OrderContent} from './ordercontent/OrderContent'
export { default as StoryContent} from './storycontent/StoryContent'
export { default as MenuContent} from './menucontent/MenuContent'
export { default as UserDashboardContent} from './userdashboardcontent/UserDashboardContent'
