export { default as Footer} from './footer/Footer'
export { default as HeaderContent} from './homecontent/HomeContent'
export { default as IntroContent} from './homecontent/IntroContent'
export { default as ContactContent} from './homecontent/ContactContent'
export { default as OrderContent} from './ordercontent/OrderContent'
export { default as MenuContent} from './menucontent/MenuContent'
export { default as UserDashboardContent} from './userdashboardcontent/UserDashboardContent'
