export { default as SliceMenu} from './slicemenu/SliceMenu'
export { default as SliceStory} from './slicestory/SliceStory'
export { default as SliceHome} from './slicehome/SliceHome'
export { default as SliceBooking} from './slicebooking/SliceBooking'
export { default as SliceUserDashboard} from './sliceuserdashboard/SliceUserDashboard'
export { default as SliceSignUp} from './slicesignup/SliceSignUp'
export { default as NotFound} from './notfound/NotFound'
