export { default as SliceMenu} from './SliceMenu'
export { default as SliceHome} from './SliceHome'
export { default as SliceBooking} from './SliceBooking'
export { default as SliceContact} from './SliceContact'
export { default as SliceUserDashboard} from './SliceUserDashboard'
export { default as NotFound} from './NotFound'
export { default as SliceCatering} from './SliceCatering'
